### ISSUE TITLE
module 'time' has no attribute 'Sleep'

### ISSUE THREAD

**Issue by crack00r** [TheRoboKitten/ZenAii#14]
Starting Trade of: OMNI-BTC
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "trader.py", line 100, in runitt
    time.Sleep(1800)
AttributeError: module 'time' has no attribute 'Sleep'
(MessageIdInvalidError(...), 'The specified message ID is invalid.')
fetching pre-roll data:

**Comment by crack00r** [comment]
https://github.com/TheRoboKitten/ZenAii/pull/16
