### ISSUE TITLE
Buy Order Rejected

### ISSUE THREAD

**Issue by Optictrollz** [TheRoboKitten/ZenAii#18]
After uncommenting lines 171 and 182 in engine.js my orders keep getting rejected.

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

order status: rejected, bid: 0.06990724, -0.00035053 below best bid, 0.0% filled

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

order status: rejected, bid: 0.06990724, -0.00035053 below best bid, 0.0% filled

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

order status: rejected, bid: 0.06990724, -0.00035053 below best bid, 0.0% filled

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

order status: rejected, bid: 0.06990724, -0.00035053 below best bid, 0.0% filled

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

order status: rejected, bid: 0.06990724, -0.00035053 below best bid, 0.0% filled

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

order status: rejected, bid: 0.06990724, -0.00035053 below best bid, 0.0% filled

placing buy order at 0.0699072 BTC, -0.00024382 BTC under best ask

order status: rejected, bid: 0.06990724, -0.00035053 below best bid, 0.0% filled

**Comment by Optictrollz** [comment]
@crack00r @TheRoboKitten

**Comment by Optictrollz** [comment]
partial = self._socket.recv(bytes_left)
BlockingIOError: [Errno 11] Resource temporarily unavailable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "traderdev4.py", line 30, in <module>
    client.connect()
  File "/home/masternode/Documents/ZenAii-master/telethon/telegram_client.py", line 140, in connect
    return super().connect()
  File "/home/masternode/Documents/ZenAii-master/telethon/telegram_bare_client.py", line 134, in connect
    layer=layer, query=request
  File "/home/masternode/Documents/ZenAii-master/telethon/telegram_client.py", line 199, in invoke
    request, updates=updates
  File "/home/masternode/Documents/ZenAii-master/telethon/telegram_bare_client.py", line 284, in invoke
    self._sender.receive(request, updates=updates)
  File "/home/masternode/Documents/ZenAii-master/telethon/network/mtproto_sender.py", line 104, in receive
    seq, body = self.transport.receive(**kwargs)
  File "/home/masternode/Documents/ZenAii-master/telethon/network/tcp_transport.py", line 56, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/home/masternode/Documents/ZenAii-master/telethon/extensions/tcp_client.py", line 115, in read
    'The read operation exceeded the timeout.') from error
TimeoutError: The read operation exceeded the timeout.
masternode@masternode-VirtualBox:~/Documents/ZenAii-master$ sudo python3 traderdev5.py
CryptoAlert Auto-Trader, with live updates...
CryptoAlert Auto-Trader, with live updates...
CryptoAlert Auto-Trader, with live updates...
CTRL-C To exit
CTRL-C To exit
CTRL-C To exit
To test me, type a coin into the cryptoping telegram bot window on telegram such as #LTC and #DASH
The Telegram updates in a while loop, and creates a pid equialent... delete coin.run if exiting in the middle of a sell signal
Traceback (most recent call last):
  File "/home/masternode/Documents/ZenAii-master/telethon/extensions/tcp_client.py", line 97, in read
    partial = self._socket.recv(bytes_left)
BlockingIOError: [Errno 11] Resource temporarily unavailable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "traderdev5.py", line 32, in <module>
    client.connect()
  File "/home/masternode/Documents/ZenAii-master/telethon/telegram_client.py", line 140, in connect
    return super().connect()
  File "/home/masternode/Documents/ZenAii-master/telethon/telegram_bare_client.py", line 134, in connect
    layer=layer, query=request
  File "/home/masternode/Documents/ZenAii-master/telethon/telegram_client.py", line 199, in invoke
    request, updates=updates
  File "/home/masternode/Documents/ZenAii-master/telethon/telegram_bare_client.py", line 284, in invoke
    self._sender.receive(request, updates=updates)
  File "/home/masternode/Documents/ZenAii-master/telethon/network/mtproto_sender.py", line 104, in receive
    seq, body = self.transport.receive(**kwargs)
  File "/home/masternode/Documents/ZenAii-master/telethon/network/tcp_transport.py", line 56, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/home/masternode/Documents/ZenAii-master/telethon/extensions/tcp_client.py", line 115, in read
    'The read operation exceeded the timeout.') from error
TimeoutError: The read operation exceeded the timeout.

I get this aswell
